/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telaLogin;

/**
 *
 * @author Guilherme
 */
public class InfoCurs extends javax.swing.JFrame {

    /**
     * Creates new form InfoCurs
     */
    public InfoCurs() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel1 = new javax.swing.JPanel();
        voltar = new javax.swing.JButton();
        imagem2 = new javax.swing.JLabel();
        imagem1 = new javax.swing.JLabel();
        painel2 = new javax.swing.JPanel();
        textoInfoCurso = new javax.swing.JLabel();
        icone = new javax.swing.JLabel();
        textoInfoCurso1 = new javax.swing.JLabel();
        painel = new javax.swing.JScrollPane();
        caixaDeTexto = new javax.swing.JTextArea();
        painel3 = new javax.swing.JPanel();
        textoSemestreAtual = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        painel1.setBackground(new java.awt.Color(20, 101, 81));
        painel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        voltar.setBackground(new java.awt.Color(88, 154, 141));
        voltar.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        voltar.setText("<<<");
        voltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        painel1.add(voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, 32));

        imagem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/planta.png"))); // NOI18N
        painel1.add(imagem2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 322, 241, 278));

        imagem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/planta2.png"))); // NOI18N
        painel1.add(imagem1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -10, 177, 224));

        getContentPane().add(painel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 600));

        painel2.setBackground(new java.awt.Color(88, 154, 141));
        painel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textoInfoCurso.setFont(new java.awt.Font("Yu Gothic UI", 3, 46)); // NOI18N
        textoInfoCurso.setText("Informações do Curso");
        painel2.add(textoInfoCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 21, 472, -1));

        icone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/infoicon.png"))); // NOI18N
        painel2.add(icone, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 21, -1, 59));

        textoInfoCurso1.setFont(new java.awt.Font("Yu Gothic UI", 3, 46)); // NOI18N
        textoInfoCurso1.setForeground(new java.awt.Color(94, 94, 94));
        textoInfoCurso1.setText("Informações do Curso");
        painel2.add(textoInfoCurso1, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 23, 472, -1));

        getContentPane().add(painel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 590, 100));

        caixaDeTexto.setEditable(false);
        caixaDeTexto.setBackground(new java.awt.Color(88, 154, 141));
        caixaDeTexto.setColumns(20);
        caixaDeTexto.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        caixaDeTexto.setRows(5);
        caixaDeTexto.setText("Nome do curso: Sistemas de Informação.\nCarga horária: 2000 horas.\nTurno: Matutino.\nTurma: A.\nSala: 20.\nSemestres: 8 semestres.\nMatérias ativas:\n-Modelagem de Software.\n-Programação de Sistemas Computacionais.");
        caixaDeTexto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.white, java.awt.Color.darkGray, java.awt.Color.white));
        painel.setViewportView(caixaDeTexto);

        getContentPane().add(painel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 510, 310));

        painel3.setBackground(new java.awt.Color(197, 220, 213));

        textoSemestreAtual.setFont(new java.awt.Font("Yu Gothic UI", 3, 35)); // NOI18N
        textoSemestreAtual.setText("Semestre atual: 1°");

        javax.swing.GroupLayout painel3Layout = new javax.swing.GroupLayout(painel3);
        painel3.setLayout(painel3Layout);
        painel3Layout.setHorizontalGroup(
            painel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel3Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(textoSemestreAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(147, Short.MAX_VALUE))
        );
        painel3Layout.setVerticalGroup(
            painel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel3Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(textoSemestreAtual)
                .addContainerGap(401, Short.MAX_VALUE))
        );

        getContentPane().add(painel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 590, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        SistemaAluno alu = new SistemaAluno();
        alu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_voltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InfoCurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InfoCurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InfoCurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InfoCurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InfoCurs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea caixaDeTexto;
    private javax.swing.JLabel icone;
    private javax.swing.JLabel imagem1;
    private javax.swing.JLabel imagem2;
    private javax.swing.JScrollPane painel;
    private javax.swing.JPanel painel1;
    private javax.swing.JPanel painel2;
    private javax.swing.JPanel painel3;
    private javax.swing.JLabel textoInfoCurso;
    private javax.swing.JLabel textoInfoCurso1;
    private javax.swing.JLabel textoSemestreAtual;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
