/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telaLogin;

import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author Guilherme
 */
public class SistemaFunc extends javax.swing.JFrame {

    ArrayList<Aluno> arrayListAl;
    DefaultListModel df;
    public SistemaFunc() {
        df = new DefaultListModel();
        arrayListAl = new ArrayList();
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        painel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        voltar = new javax.swing.JButton();
        imagem = new javax.swing.JLabel();
        painel2 = new javax.swing.JPanel();
        textoCadastroAlu = new javax.swing.JLabel();
        icone = new javax.swing.JLabel();
        textoCadastroAlu1 = new javax.swing.JLabel();
        idade = new javax.swing.JTextField();
        botF = new javax.swing.JRadioButton();
        botI = new javax.swing.JRadioButton();
        botM = new javax.swing.JRadioButton();
        separador = new javax.swing.JSeparator();
        painel3 = new javax.swing.JPanel();
        apagar = new javax.swing.JButton();
        entrar = new javax.swing.JButton();
        alunosCadastrados = new javax.swing.JLabel();
        digiteCidade = new javax.swing.JLabel();
        selecioneCurso = new javax.swing.JLabel();
        curso = new javax.swing.JComboBox<>();
        cidade = new javax.swing.JTextField();
        selecioneSexo = new javax.swing.JLabel();
        digiteNome = new javax.swing.JLabel();
        digiteIdade = new javax.swing.JLabel();
        digiteRA = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        ra = new javax.swing.JTextField();
        detalhesAlunos = new javax.swing.JLabel();
        painelScroll1 = new javax.swing.JScrollPane();
        lista = new javax.swing.JList<>();
        painelScroll2 = new javax.swing.JScrollPane();
        areaInfo = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        painel1.setBackground(new java.awt.Color(20, 101, 81));
        painel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/planta.png"))); // NOI18N
        painel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 319, 206, -1));

        voltar.setBackground(new java.awt.Color(88, 154, 141));
        voltar.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        voltar.setText("<<<");
        voltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        painel1.add(voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, 32));

        imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/planta2.png"))); // NOI18N
        imagem.setText("jLabel2");
        painel1.add(imagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -10, 177, 224));

        getContentPane().add(painel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 0, 170, 600));

        painel2.setBackground(new java.awt.Color(88, 154, 141));
        painel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textoCadastroAlu.setFont(new java.awt.Font("Yu Gothic UI", 3, 48)); // NOI18N
        textoCadastroAlu.setText("Cadastro de Alunos");
        painel2.add(textoCadastroAlu, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 25, 438, -1));

        icone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cadastrafunc.png"))); // NOI18N
        painel2.add(icone, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 29, -1, -1));

        textoCadastroAlu1.setFont(new java.awt.Font("Yu Gothic UI", 3, 48)); // NOI18N
        textoCadastroAlu1.setForeground(new java.awt.Color(94, 94, 94));
        textoCadastroAlu1.setText("Cadastro de Alunos");
        painel2.add(textoCadastroAlu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 27, 438, -1));

        getContentPane().add(painel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 620, 110));

        idade.setBackground(new java.awt.Color(88, 154, 141));
        idade.setFont(new java.awt.Font("Yu Gothic Light", 0, 12)); // NOI18N
        getContentPane().add(idade, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 170, 30));

        buttonGroup1.add(botF);
        botF.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        botF.setText("Feminino");
        botF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(botF, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 80, -1));

        buttonGroup1.add(botI);
        botI.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        botI.setText("Prefiro não dizer");
        botI.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(botI, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, -1, -1));

        buttonGroup1.add(botM);
        botM.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        botM.setText("Masculino");
        botM.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(botM, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, -1, -1));

        separador.setBackground(new java.awt.Color(0, 0, 0));
        separador.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(separador, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 343, 600, 10));

        painel3.setBackground(new java.awt.Color(197, 220, 213));

        apagar.setBackground(new java.awt.Color(88, 154, 141));
        apagar.setFont(new java.awt.Font("Yu Gothic UI", 1, 16)); // NOI18N
        apagar.setText("Apagar");
        apagar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        apagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apagarActionPerformed(evt);
            }
        });
        apagar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                apagarKeyPressed(evt);
            }
        });

        entrar.setBackground(new java.awt.Color(88, 154, 141));
        entrar.setFont(new java.awt.Font("Yu Gothic UI", 1, 16)); // NOI18N
        entrar.setText("Cadastrar");
        entrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarActionPerformed(evt);
            }
        });

        alunosCadastrados.setFont(new java.awt.Font("Yu Gothic UI", 1, 20)); // NOI18N
        alunosCadastrados.setText("Alunos Cadastrados");

        digiteCidade.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        digiteCidade.setText("Cidade:");

        selecioneCurso.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        selecioneCurso.setText("Curso:");

        curso.setBackground(new java.awt.Color(88, 154, 141));
        curso.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        curso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sistema de Informação", "Ciência da Computação", "Análise e Desenvolvimento de Sistemas" }));
        curso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        cidade.setBackground(new java.awt.Color(88, 154, 141));
        cidade.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N

        selecioneSexo.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        selecioneSexo.setText("Sexo:");

        digiteNome.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        digiteNome.setText("Nome:");

        digiteIdade.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        digiteIdade.setText("Idade:");

        digiteRA.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        digiteRA.setText("RA:");

        nome.setBackground(new java.awt.Color(88, 154, 141));
        nome.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N

        ra.setBackground(new java.awt.Color(88, 154, 141));
        ra.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ra.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        detalhesAlunos.setFont(new java.awt.Font("Yu Gothic UI", 1, 20)); // NOI18N
        detalhesAlunos.setText("Detalhes Alunos");

        lista.setBackground(new java.awt.Color(88, 154, 141));
        lista.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.white, java.awt.Color.darkGray, java.awt.Color.white));
        lista.setFont(new java.awt.Font("Yu Gothic UI", 0, 23)); // NOI18N
        lista.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaValueChanged(evt);
            }
        });
        painelScroll1.setViewportView(lista);

        areaInfo.setEditable(false);
        areaInfo.setBackground(new java.awt.Color(88, 154, 141));
        areaInfo.setColumns(20);
        areaInfo.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        areaInfo.setRows(5);
        areaInfo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.white, java.awt.Color.darkGray, java.awt.Color.white));
        painelScroll2.setViewportView(areaInfo);

        javax.swing.GroupLayout painel3Layout = new javax.swing.GroupLayout(painel3);
        painel3.setLayout(painel3Layout);
        painel3Layout.setHorizontalGroup(
            painel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel3Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(painel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painel3Layout.createSequentialGroup()
                        .addComponent(digiteIdade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(entrar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88))
                    .addGroup(painel3Layout.createSequentialGroup()
                        .addGroup(painel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(selecioneSexo)
                            .addGroup(painel3Layout.createSequentialGroup()
                                .addGroup(painel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(digiteNome)
                                    .addComponent(digiteRA))
                                .addGap(33, 33, 33)
                                .addGroup(painel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ra, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(painel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                                .addGroup(painel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(selecioneCurso)
                                    .addComponent(digiteCidade))
                                .addGap(28, 28, 28)
                                .addGroup(painel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(curso, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(48, 48, 48))
                            .addGroup(painel3Layout.createSequentialGroup()
                                .addGap(111, 111, 111)
                                .addGroup(painel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(detalhesAlunos)
                                    .addComponent(apagar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
            .addGroup(painel3Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(alunosCadastrados)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(painel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(painelScroll1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(painelScroll2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        painel3Layout.setVerticalGroup(
            painel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(painel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(digiteNome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selecioneCurso)
                    .addComponent(curso, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(painel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(selecioneSexo)
                        .addGap(47, 47, 47)
                        .addComponent(digiteIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painel3Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(painel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(digiteCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(entrar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(painel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(apagar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ra, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(digiteRA))))
                .addGap(27, 27, 27)
                .addGroup(painel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alunosCadastrados)
                    .addComponent(detalhesAlunos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelScroll2)
                    .addComponent(painelScroll1, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(painel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 620, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarActionPerformed
        Aluno alu = new Aluno();
        alu.setNome(nome.getText());
        alu.setIdade(Integer.parseInt(idade.getText()));
        alu.setCidade(cidade.getText());
        alu.setRa(Integer.parseInt(ra.getText()));
        alu.setCurso(curso.getSelectedItem().toString());
        if(botM.isSelected()){
            alu.setSexo("masculino");
        } else if(botF.isSelected()){
            alu.setSexo("feminino");
        } else if(botI.isSelected()){
            alu.setSexo("prefiro não dizer");
        }
        
        arrayListAl.add(alu);
        df.addElement(alu.getNome());
        lista.setModel(df);       
    }//GEN-LAST:event_entrarActionPerformed

    private void listaValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaValueChanged

        for(Aluno alu: arrayListAl){
            if(alu.getNome().equalsIgnoreCase(lista.getSelectedValue())){
                areaInfo.setText(alu.imprimir());
            }
        }
    }//GEN-LAST:event_listaValueChanged

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        TelaLoginFuncionario func = new TelaLoginFuncionario();
        func.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_voltarActionPerformed

    private void apagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apagarActionPerformed
        for(Aluno alu: arrayListAl){
            if(alu.getNome().equalsIgnoreCase(lista.getSelectedValue())){
                df.remove(lista.getSelectedIndex());
                areaInfo.setText(alu.imprimirVazio());               
            }
        }
    }//GEN-LAST:event_apagarActionPerformed

    private void apagarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_apagarKeyPressed
        for(Aluno alu: arrayListAl){
            if(alu.getNome().equalsIgnoreCase(lista.getSelectedValue())){
                arrayListAl.remove(lista.getSelectedValue());
            }
        }
    }//GEN-LAST:event_apagarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SistemaFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SistemaFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SistemaFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SistemaFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SistemaFunc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alunosCadastrados;
    private javax.swing.JButton apagar;
    private javax.swing.JTextArea areaInfo;
    private javax.swing.JRadioButton botF;
    private javax.swing.JRadioButton botI;
    private javax.swing.JRadioButton botM;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField cidade;
    private javax.swing.JComboBox<String> curso;
    private javax.swing.JLabel detalhesAlunos;
    private javax.swing.JLabel digiteCidade;
    private javax.swing.JLabel digiteIdade;
    private javax.swing.JLabel digiteNome;
    private javax.swing.JLabel digiteRA;
    private javax.swing.JButton entrar;
    private javax.swing.JLabel icone;
    private javax.swing.JTextField idade;
    private javax.swing.JLabel imagem;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<String> lista;
    private javax.swing.JTextField nome;
    private javax.swing.JPanel painel1;
    private javax.swing.JPanel painel2;
    private javax.swing.JPanel painel3;
    private javax.swing.JScrollPane painelScroll1;
    private javax.swing.JScrollPane painelScroll2;
    private javax.swing.JTextField ra;
    private javax.swing.JLabel selecioneCurso;
    private javax.swing.JLabel selecioneSexo;
    private javax.swing.JSeparator separador;
    private javax.swing.JLabel textoCadastroAlu;
    private javax.swing.JLabel textoCadastroAlu1;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
