/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telaLogin;

import javax.swing.JOptionPane;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
/**
 *
 * @author Guilherme
 */
public class TelaLogin extends javax.swing.JFrame {
    private ArrayList<String> nomeS;

    ArrayList<Aluno> arrayListAlu;
    public TelaLogin() {
        nomeS = new ArrayList();
        arrayListAlu = new ArrayList();
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel = new javax.swing.JPanel();
        desanima = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        digitarUsuario = new javax.swing.JLabel();
        loginFunc = new javax.swing.JButton();
        apagar = new javax.swing.JButton();
        acessar = new javax.swing.JButton();
        ra = new javax.swing.JPasswordField();
        digitarRA = new javax.swing.JLabel();
        texto = new javax.swing.JLabel();
        texto1 = new javax.swing.JLabel();
        icone = new javax.swing.JLabel();
        educacao = new javax.swing.JLabel();
        imagem = new javax.swing.JLabel();
        linha = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        painel.setBackground(new java.awt.Color(197, 220, 213));
        painel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        desanima.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/desanima.png"))); // NOI18N
        painel.add(desanima, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 160, 40));

        usuario.setBackground(new java.awt.Color(88, 154, 141));
        usuario.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        usuario.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioActionPerformed(evt);
            }
        });
        usuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                usuarioKeyPressed(evt);
            }
        });
        painel.add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 409, 43));

        digitarUsuario.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        digitarUsuario.setText("Digite o seu Usuário:");
        painel.add(digitarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, -1, -1));

        loginFunc.setBackground(new java.awt.Color(88, 154, 141));
        loginFunc.setFont(new java.awt.Font("Yu Gothic UI", 3, 18)); // NOI18N
        loginFunc.setText("Login Administrativo");
        loginFunc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginFuncActionPerformed(evt);
            }
        });
        painel.add(loginFunc, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 470, 210, -1));

        apagar.setBackground(new java.awt.Color(88, 154, 141));
        apagar.setFont(new java.awt.Font("Yu Gothic UI", 3, 18)); // NOI18N
        apagar.setText("Apagar");
        apagar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        apagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apagarActionPerformed(evt);
            }
        });
        painel.add(apagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 430, 210, -1));

        acessar.setBackground(new java.awt.Color(88, 154, 141));
        acessar.setFont(new java.awt.Font("Yu Gothic UI", 3, 18)); // NOI18N
        acessar.setText("Acessar sistema");
        acessar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        acessar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acessarActionPerformed(evt);
            }
        });
        acessar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                acessarKeyPressed(evt);
            }
        });
        painel.add(acessar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, 210, -1));

        ra.setBackground(new java.awt.Color(88, 154, 141));
        ra.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        ra.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        ra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raActionPerformed(evt);
            }
        });
        ra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Senha(evt);
            }
        });
        painel.add(ra, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 410, 42));

        digitarRA.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        digitarRA.setText("Digite o seu RA:");
        painel.add(digitarRA, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 180, -1));

        texto.setFont(new java.awt.Font("Yu Gothic UI", 3, 54)); // NOI18N
        texto.setText("Login");
        painel.add(texto, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, 150, -1));

        texto1.setFont(new java.awt.Font("Yu Gothic UI", 3, 54)); // NOI18N
        texto1.setForeground(new java.awt.Color(94, 94, 94));
        texto1.setText("Login");
        painel.add(texto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 42, 150, -1));

        icone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/usericon.png"))); // NOI18N
        painel.add(icone, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, -1, -1));

        educacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/educacao.png"))); // NOI18N
        painel.add(educacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/png.png"))); // NOI18N
        painel.add(imagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, -1));

        linha.setBackground(new java.awt.Color(0, 0, 0));
        linha.setForeground(new java.awt.Color(0, 0, 0));
        painel.add(linha, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 760, 10));

        getContentPane().add(painel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public ArrayList<String> getArray(){
        return nomeS;
    }  
    private void raActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raActionPerformed
        
    }//GEN-LAST:event_raActionPerformed

    private void apagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apagarActionPerformed
        ra.setText("");
        usuario.grabFocus();
        usuario.setText("");
    }//GEN-LAST:event_apagarActionPerformed

    private void Senha(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Senha
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            acessar.grabFocus();
        }
    }//GEN-LAST:event_Senha

    private void usuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usuarioKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            ra.grabFocus(); 
            nomeS.add(usuario.getText());
        }
    }//GEN-LAST:event_usuarioKeyPressed

    private void usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioActionPerformed
        nomeS.add(usuario.getText());
    }//GEN-LAST:event_usuarioActionPerformed

    private void loginFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginFuncActionPerformed
        TelaLoginFuncionario func = new TelaLoginFuncionario();
        func.setVisible(true);
        this.dispose();  
    }//GEN-LAST:event_loginFuncActionPerformed

    private void acessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acessarActionPerformed
           if(usuario.getText().equalsIgnoreCase("guilherme") && String.valueOf(ra.getPassword()).equals("123")){
            SistemaAluno sist = new SistemaAluno();
            sist.setVisible(true);
            this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Usuário ou senha inválida");
             usuario.grabFocus();
        }
    }//GEN-LAST:event_acessarActionPerformed

    private void acessarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_acessarKeyPressed
         if(usuario.getText().equalsIgnoreCase("guilherme") && String.valueOf(ra.getPassword()).equals("123")){
            SistemaAluno sist = new SistemaAluno();
            sist.setVisible(true);
            this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Usuário ou senha inválida");
             usuario.grabFocus();
        }
    }//GEN-LAST:event_acessarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
               // TelaLogin tela = new TelaLogin();
                //tela.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acessar;
    private javax.swing.JButton apagar;
    private javax.swing.JLabel desanima;
    private javax.swing.JLabel digitarRA;
    private javax.swing.JLabel digitarUsuario;
    private javax.swing.JLabel educacao;
    private javax.swing.JLabel icone;
    private javax.swing.JLabel imagem;
    private javax.swing.JSeparator linha;
    private javax.swing.JButton loginFunc;
    private javax.swing.JPanel painel;
    private javax.swing.JPasswordField ra;
    private javax.swing.JLabel texto;
    private javax.swing.JLabel texto1;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
