/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telaLogin;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Guilherme
 */
public class TelaLoginFuncionario extends javax.swing.JFrame {

    /**
     * Creates new form telaLoginFuncionario
     */
    public TelaLoginFuncionario() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        digiteUsuario = new javax.swing.JLabel();
        digiteSenha = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        senha = new javax.swing.JPasswordField();
        texto = new javax.swing.JLabel();
        texto1 = new javax.swing.JLabel();
        acessar = new javax.swing.JButton();
        apagar = new javax.swing.JButton();
        voltar = new javax.swing.JButton();
        icone = new javax.swing.JLabel();
        imagem = new javax.swing.JLabel();
        separador = new javax.swing.JSeparator();
        painel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        digiteUsuario.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        digiteUsuario.setText("Digite o seu Usuário:");
        getContentPane().add(digiteUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, -1, -1));

        digiteSenha.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        digiteSenha.setText("Digite a sua Senha:");
        getContentPane().add(digiteSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, -1, -1));

        usuario.setBackground(new java.awt.Color(88, 154, 141));
        usuario.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        usuario.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioActionPerformed(evt);
            }
        });
        getContentPane().add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 404, 50));

        senha.setBackground(new java.awt.Color(88, 154, 141));
        senha.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        senha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                senhaKeyPressed(evt);
            }
        });
        getContentPane().add(senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 404, 50));

        texto.setFont(new java.awt.Font("Yu Gothic UI", 3, 50)); // NOI18N
        texto.setText("Login Administrativo");
        getContentPane().add(texto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 480, -1));

        texto1.setFont(new java.awt.Font("Yu Gothic UI", 3, 50)); // NOI18N
        texto1.setForeground(new java.awt.Color(94, 94, 94));
        texto1.setText("Login Administrativo");
        texto1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(texto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 42, 480, -1));

        acessar.setBackground(new java.awt.Color(88, 154, 141));
        acessar.setFont(new java.awt.Font("Yu Gothic UI", 3, 17)); // NOI18N
        acessar.setText("Acessar Sistema");
        acessar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        acessar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acessarActionPerformed(evt);
            }
        });
        acessar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                acessarKeyPressed(evt);
            }
        });
        getContentPane().add(acessar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, 203, -1));

        apagar.setBackground(new java.awt.Color(88, 154, 141));
        apagar.setFont(new java.awt.Font("Yu Gothic UI", 3, 17)); // NOI18N
        apagar.setText("Apagar");
        apagar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        apagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apagarActionPerformed(evt);
            }
        });
        getContentPane().add(apagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 480, 203, -1));

        voltar.setBackground(new java.awt.Color(88, 154, 141));
        voltar.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        voltar.setText("<<<");
        voltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        getContentPane().add(voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, 31));

        icone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/usericon.png"))); // NOI18N
        getContentPane().add(icone, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, -1));

        imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/png.png"))); // NOI18N
        getContentPane().add(imagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 600));

        separador.setBackground(new java.awt.Color(0, 0, 0));
        separador.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(separador, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 760, 10));

        painel.setBackground(new java.awt.Color(197, 220, 213));
        painel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(painel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioActionPerformed
        
    }//GEN-LAST:event_usuarioActionPerformed

    private void acessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acessarActionPerformed
        if(usuario.getText().equals("funcionario") && String.valueOf(senha.getPassword()).equals("1234")){
            SistemaFunc sist = new SistemaFunc();
            sist.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Usuário ou senha inválida");
            usuario.grabFocus();
        }
    }//GEN-LAST:event_acessarActionPerformed

    private void apagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apagarActionPerformed
        senha.setText("");
        usuario.grabFocus();
        usuario.setText("");
    }//GEN-LAST:event_apagarActionPerformed

    private void acessarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_acessarKeyPressed
        if(usuario.getText().equals("funcionario") && String.valueOf(senha.getPassword()).equals("1234")){
            SistemaFunc sist = new SistemaFunc();
            sist.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Usuário ou senha inválida");
            usuario.grabFocus();
        }
    }//GEN-LAST:event_acessarKeyPressed

    private void senhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_senhaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            acessar.grabFocus();
        }
    }//GEN-LAST:event_senhaKeyPressed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        TelaLogin lgn = new TelaLogin();
        lgn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_voltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLoginFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLoginFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLoginFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLoginFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLoginFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acessar;
    private javax.swing.JButton apagar;
    private javax.swing.JLabel digiteSenha;
    private javax.swing.JLabel digiteUsuario;
    private javax.swing.JLabel icone;
    private javax.swing.JLabel imagem;
    private javax.swing.JPanel painel;
    private javax.swing.JPasswordField senha;
    private javax.swing.JSeparator separador;
    private javax.swing.JLabel texto;
    private javax.swing.JLabel texto1;
    private javax.swing.JTextField usuario;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
